# Generated by Django 4.2.16 on 2026-05-28 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organisation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="ingestion.organisation",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IngestionBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("sap", "SAP Fuel & Procurement"),
                            ("utility", "Utility / Electricity"),
                            ("travel", "Corporate Travel"),
                        ],
                        max_length=20,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("original_filename", models.CharField(blank=True, max_length=500)),
                (
                    "raw_file",
                    models.FileField(blank=True, null=True, upload_to="uploads/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("row_count", models.IntegerField(default=0)),
                ("error_count", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="ingestion.organisation",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="EmissionRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("1", "Scope 1"), ("2", "Scope 2"), ("3", "Scope 3")],
                        max_length=1,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("fuel", "Fuel"),
                            ("electricity", "Electricity"),
                            ("flight", "Flight"),
                            ("hotel", "Hotel"),
                            ("ground_transport", "Ground Transport"),
                            ("procurement", "Procurement"),
                        ],
                        max_length=30,
                    ),
                ),
                ("activity_date", models.DateField()),
                ("description", models.CharField(blank=True, max_length=500)),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                ("original_unit", models.CharField(max_length=50)),
                ("normalised_unit", models.CharField(max_length=50)),
                (
                    "normalised_quantity",
                    models.DecimalField(decimal_places=4, max_digits=18),
                ),
                (
                    "co2e_kg",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "source_row_id",
                    models.CharField(
                        blank=True,
                        help_text="Row ID / doc number from source system",
                        max_length=200,
                    ),
                ),
                (
                    "source_plant_code",
                    models.CharField(
                        blank=True, help_text="SAP plant/cost centre", max_length=100
                    ),
                ),
                (
                    "source_meter_id",
                    models.CharField(
                        blank=True, help_text="Utility meter reference", max_length=100
                    ),
                ),
                ("source_vendor", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("flagged", "Flagged / Suspicious"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("reviewer_note", models.TextField(blank=True)),
                ("is_suspicious", models.BooleanField(default=False)),
                ("suspicion_reason", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("locked", models.BooleanField(default=False)),
                ("raw_data", models.JSONField(default=dict)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="ingestion.ingestionbatch",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="ingestion.organisation",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-activity_date"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("action", models.CharField(max_length=100)),
                ("before", models.JSONField(default=dict)),
                ("after", models.JSONField(default=dict)),
                ("note", models.TextField(blank=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="ingestion.emissionrecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-changed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="emissionrecord",
            index=models.Index(
                fields=["organisation", "scope"], name="ingestion_e_organis_bff3f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emissionrecord",
            index=models.Index(
                fields=["organisation", "status"], name="ingestion_e_organis_e2aaec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emissionrecord",
            index=models.Index(fields=["batch"], name="ingestion_e_batch_i_e7d0fe_idx"),
        ),
        migrations.AddIndex(
            model_name="emissionrecord",
            index=models.Index(
                fields=["activity_date"], name="ingestion_e_activit_d0ada0_idx"
            ),
        ),
    ]
